'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Images
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tempestas.Images", GetType(Images).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property AboutScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property add2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnAddDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAddDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnAddDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAddDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnAddUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnAddUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBackDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBackDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBackUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBrowseDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBrowseDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBrowseDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBrowseDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnBrowseUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBrowseUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCancelDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancelDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCancelDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancelDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCancelUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancelUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCreateDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCreateDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCreateDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCreateDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnCreateUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCreateUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnDeleteDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDeleteDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnDeleteDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDeleteDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnDeleteUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDeleteUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLeftEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLeftEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoadDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoadDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoadDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoadDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoadUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoadUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoginDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoginDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoginDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoginDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnLoginUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLoginUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnModifyDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModifyDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnModifyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModifyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnModifyUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnModifyUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNewDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNewDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNewDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNewDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNewUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNewUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNextDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNextDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNextDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNextDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnNextUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNextUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnOKDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOKDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnOKDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOKDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnOKUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOKUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnSendDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSendDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnSendDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSendDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnSendUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSendUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnUpdateDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnUpdateDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnUpdateDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnUpdateDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property btnUpdateUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnUpdateUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property businessman_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessman_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property document_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property export1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property folder_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property media_play_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_play_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property preferences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property SplashScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SplashScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property table_sql_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_sql_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property table_sql_select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_sql_select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property table_sql_view() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("table_sql_view", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Class
End Namespace
